# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ajaxful_rating}
  s.version = "3.0.0.beta3"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.authors = ["Edgar J. Suarez", "Denis Odorcic"]
  s.date = %q{2010-10-14}
  s.description = %q{Provides a simple way to add rating functionality to your application.}
  s.email = ["edgar.js@gmail.com", "denis.odorcic@gmail.com"]
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "Manifest",
     "README.textile",
     "Rakefile",
     "ajaxful_rating.gemspec",
     "lib/ajaxful_rating.rb",
     "lib/axr/css_builder.rb",
     "lib/axr/errors.rb",
     "lib/axr/helpers.rb",
     "lib/axr/locale.rb",
     "lib/axr/model.rb",
     "lib/axr/stars_builder.rb",
     "lib/generators/ajaxful_rating/USAGE",
     "lib/generators/ajaxful_rating/ajaxful_rating_generator.rb",
     "lib/generators/ajaxful_rating/templates/images/star.png",
     "lib/generators/ajaxful_rating/templates/images/star_small.png",
     "lib/generators/ajaxful_rating/templates/migration.rb",
     "lib/generators/ajaxful_rating/templates/model.rb",
     "lib/generators/ajaxful_rating/templates/style.css",
     "test/fixtures/car.rb",
     "test/fixtures/cars.yml",
     "test/fixtures/rate.rb",
     "test/fixtures/rates.yml",
     "test/fixtures/schema.rb",
     "test/fixtures/user.rb",
     "test/fixtures/users.yml",
     "test/lib/model_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/edgarjs/ajaxful-rating}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Provides a simple way to add rating functionality to your application.}
  s.test_files = [
    "test/fixtures/car.rb",
     "test/fixtures/rate.rb",
     "test/fixtures/schema.rb",
     "test/fixtures/user.rb",
     "test/lib/model_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

